"""added freelancer model

Revision ID: 999710413127
Revises: fa8ddbfe958b
Create Date: 2020-01-26 00:22:33.576201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999710413127'
down_revision = 'fa8ddbfe958b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freelancer')
    # ### end Alembic commands ###
